### ISSUE TITLE
Waterrower USB serial available in Flutter

### ISSUE THREAD

**Issue by sctajc** [tbressler/waterrower-core#22]
I'm trying to develop an open source Waterrower app in Flutter. It is based on Coxswain from a functionally point of view (https://github.com/sctajc/coxswain_sctajc). I'm new to programming and one thing I am struggling with is how with using a USB cable, to get the S4 feed info to my app. I'm keen on Flutter as one code base can then run on Android, IOS, Windows etc. Any ideas on what my approach should be? Your library looks like it would do the right thing but I have no idea if I can use Java within Flutter. Or if there is another approach I should use.

**Comment by tbressler** [comment]
Unfortunately I don't have much experience with Flutter, but I try to answer your question as best as I can.

From my point of view there are 2 reason why your idea will not work:
1. Because Flutter is based on Dart there is no easy way of using a Java library I guess.
2. The waterrower-core library currently supports MacOS, Windows and Linux. The library is based on the jSerialComm library for Java. Unfortunately there is no port for Android and iOS of this library available. So even if you write a native Android application and use my library, this will not work.
